import os

from telethon.sync import TelegramClient
from telethon.sessions import StringSession

api_id = int(os.getenv("API_ID") or input("Enter your API_ID: "))
api_hash = os.getenv("API_HASH") or input("Enter your API_HASH: ")

with TelegramClient(StringSession(), api_id, api_hash) as client: 
    session_str = client.session.save()
    if client.is_bot():
        user_name = input("Enter your account username: ")
        msg = client.send_message(user_name, f"`{session_str}`\n\n**NOTE:** This session string is generated by tg-index and is only usable with **Telethon** based projects.")
    else:
        msg = client.send_message("me", f"`{session_str}`\n\n**NOTE:** This session string is generated by tg-index and is only usable with **Telethon** based projects.")
        print("\nPlease check your Telegram Saved Messages/User's PM for the session string.")
